### PR TITLE
Catch potentially site-bricking error caused by improperly formatted …

### PR DESCRIPTION
**Pull request by obct537**
…image scale

Might not be the perfect approach here?

Fixes a major bug for us, in the event that someone inputs an improperly formatted scale.

### CODE REVIEW

**Comment by gforcada** [comment]
@obct537 do you have an image that causes this? It would be great to have it in a test so we don't have a regression later on.

**Comment by obct537** [comment]
@gforcada I think I'm going to actually retract this PR, unless you think it's still valuable. The issue I was experiencing, although closely related, wasn't really being caused by plone.app.imaging. My mistake.

**Comment by gforcada** [comment]
@obct537 yes, if it is not related to this changes that you made, it does not make sense to merge this.

Out of curiosity, did it had anything to do with another Plone package or was a problem outside Plone?

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
