### PR TITLE
Issue 16 - Fix incompatibilities with five.pt and chameleon

### LINKED ISSUE #16: Incompatibilities with five.pt
As we notice into these issues (https://github.com/zopefoundation/five.pt/issues/5 and https://github.com/malthe/chameleon/issues/59) we have some incompatibilities with `five.pt` and `chameleon`.

In summary, `plone.app.imaging` is waiting for a `list` while `chameleon` uses a `tuple` instead as an speed optimization.

In this issue, we should make `plone.app.imaging` accept a `tuple` as an argument.

### PR DESCRIPTION
**Pull request by rodfersou**
closes #16

### CODE REVIEW

**Comment by pbauer** [comment]
Jenkins PR job: jenkins.plone.org/job/pull-request-5.0/237/

**Comment by rodfersou** [comment]
Running tests here: http://jenkins.plone.org/job/pull-request-4.3/159/

**Comment by rodfersou** [comment]
Running tests here: http://jenkins.plone.org/job/pull-request-5.0/552/

**Comment by rodfersou** [comment]
green!

**Comment by rodfersou** [comment]
@gforcada 

Total | Failed | Passed | Pass %
------- | -------- | ---------- | ----------
Critical tests | 111 | 0 | 111 | 100.0
All tests | 111 | 0 | 111 | 100.0

**Comment by rodfersou** [comment]
Oh.. now I see.. that table is just for RF tests

**Comment by mauritsvanrees** [comment]
Closing this one in favour of #23.

**Pull request closed without merging**
