### PR TITLE
Issue 16 1.0.x - Fix incompatibilities with five.pt and chameleon

### LINKED ISSUE #16: Incompatibilities with five.pt
As we notice into these issues (https://github.com/zopefoundation/five.pt/issues/5 and https://github.com/malthe/chameleon/issues/59) we have some incompatibilities with `five.pt` and `chameleon`.

In summary, `plone.app.imaging` is waiting for a `list` while `chameleon` uses a `tuple` instead as an speed optimization.

In this issue, we should make `plone.app.imaging` accept a `tuple` as an argument.

### PR DESCRIPTION
**Pull request by rodfersou**
closes #16

### CODE REVIEW

**Comment by pbauer** [comment]
Jenkins PR job: http://jenkins.plone.org/job/pull-request-4.3/84/

**Comment by pbauer** [comment]
@rodfersou 2 tests are failing: http://jenkins.plone.org/job/pull-request-4.3/84/testReport/

**Comment by rodfersou** [comment]
Running tests here: http://jenkins.plone.org/job/pull-request-4.3/160/

**Comment by hvelarde** [comment]
green!

**Comment by mauritsvanrees** [comment]
The robot tests are green, but there are two failures in the rest of the tests, both in  `plone.app.imaging.tests.test_new_scaling.ImagePublisherTests`:
http://jenkins.plone.org/job/pull-request-4.3/160/testReport/

**Comment by mauritsvanrees** [comment]
With the fix of this pull request, when I use Plone coredev 4.3 and add five.pt, and I add this line to `Products/CMFPlone/skins/plone_content/image_view.pt` it fails:

```
    <img tal:replace="structure context/@@images/image/mini" />
```

Traceback is:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module b302f59dfcdc44c5e81398a2eeb4a310.py, line 744, in render
  Module 53bd359a72a55bdf6a869f9819fdfb14.py, line 1392, in render_master
  Module 53bd359a72a55bdf6a869f9819fdfb14.py, line 559, in render_content
  Module b302f59dfcdc44c5e81398a2eeb4a310.py, line 732, in __fill_content_core
  Module b302f59dfcdc44c5e81398a2eeb4a310.py, line 256, in render_content_core
  Module five.pt.expressions, line 135, in __call__
  Module five.pt.expressions, line 126, in traverse
  Module zope.traversing.adapters, line 136, in traversePathElement
   - __traceback_info__: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini')
  Module zope.traversing.adapters, line 50, in traverse
   - __traceback_info__: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini', ())
LocationError: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini')

 - Expression: "context/@@images/image/mini"
 - Filename:   ... lone/Products/CMFPlone/skins/plone_content/image_view.pt
 - Location:   (line 26: col 40)
 - Source:     ... :replace="structure context/@@images/image/mini" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper image_view at 0x106b2f1e0>
               modules: <instance - at 0x1028ba560>
               here: <ImplicitAcquisitionWrapper voeten-op-het-strand.jpg at 0x106106be0>
               user: <ImplicitAcquisitionWrapper - at 0x105db1fa0>
               nothing: <NoneType - at 0x101cf9a88>
               container: <ImplicitAcquisitionWrapper Plone at 0x1060d91e0>
               default: <object - at 0x10201eb50>
               request: <instance - at 0x1070facb0>
               wrapped_repeat: <SafeMapping - at 0x10707ecb0>
               traverse_subpath: <list - at 0x10645cf80>
               loop: {...} (1)
               context: <ImplicitAcquisitionWrapper voeten-op-het-strand.jpg at 0x106106be0>
               translate: <function translate at 0x107111b18>
               root: <ImplicitAcquisitionWrapper Zope at 0x10693b780>
               options: {...} (1)
               target_language: <NoneType - at 0x101cf9a88>
```

The same line without five.pt and with the fix from this pull request, also fails:

```
2015-11-18 17:45:25 ERROR Zope.SiteErrorLog 1447865125.510.0573804215669 http://localhost:8080/Plone/voeten-op-het-strand.jpg/image_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
...
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/Users/maurits/community/plone-coredev/4.3/src/Products.CMFPlone/Products/CMFPlone/skins/plone_content/image_view.pt
   - Line 26, Column 12
   - Expression: <PathExpr standard:u'context/@@images/image/mini'>
   - Names:
      {'container': <PloneSite at /Plone>,
       'context': <ATImage at /Plone/voeten-op-het-strand.jpg>,
       'default': <object object at 0x109a0ab50>,
       'here': <ATImage at /Plone/voeten-op-het-strand.jpg>,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x10e4d0208>,
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/voeten-op-het-strand.jpg/image_view>,
       'root': <Application at >,
       'template': <FSPageTemplate at /Plone/image_view used for /Plone/voeten-op-het-strand.jpg>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 147, in _eval
  Module zope.tales.expressions, line 124, in _eval
  Module Products.PageTemplates.Expressions, line 77, in boboAwareZopeTraverse
  Module zope.traversing.adapters, line 136, in traversePathElement
   - __traceback_info__: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini')
  Module zope.traversing.adapters, line 50, in traverse
   - __traceback_info__: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini', [])
LocationError: ('<img src="http://localhost:8080/Plone/voeten-op-het-strand.jpg/@@images/f0d21e30-7ecd-4206-a727-b8e70a03a59b.jpeg" alt="voeten-op-het-strand.jpg" title="voeten-op-het-strand.jpg" height="150" width="200" />', 'mini')
```

The same line without five.pt and with original plone.app.imaging works fine.

But yes, something definitely needs fixing, because the same line with five.pt and with original plone.app.imaging gives an error because of the popping from the tuple, which this pull request tries to solve.

The fix does look like it may help, but some problems remain. I tried something quickly, but could not directly understand how to fix it.  Anyway, this fails with this pull request:

```
bin/test -s plone.app.imaging -m test_new_scaling -t ImagePublisherTests
```

**Comment by mauritsvanrees** [comment]
http://jenkins.plone.org/job/pull-request-4.3/163/

**Comment by mauritsvanrees** [comment]
I have made a change in this pull request and now it works for me.  I have reverted your change to the `publishTraverse` method, as @hvelarde already mentioned somewhere that this method was not actually affected by five.pt: this is just accessed by the Zope publisher and always gets the path as a list.

The image traverse tests now test both the standard and the chameleon traversal.

Note that in the traverse method of the view I have made a shortcut for zope.pagetemplate, which basically is the old behavior. We can also remove this: it works just fine without it.  It might be slightly faster to keep it.  If we remove it, the code is simpler and it then uses the same code path for zope.pagetemplate and five.pt, which is nicer for the next developer who needs to fix something here or even just needs to understand what is happening. So I am actually in favour of removing this shortcut.

I have merged branch 1.0.x in here. The pull request should be squashed, but that makes it unclear what you have changed and what I have changed. And I did not want to highjack this pull request even further...

**Comment by mauritsvanrees** [comment]
Jenkins is green.

**Comment by hvelarde** [comment]
awesome, @mauritsvanrees! +1 on removing the old behavior.

**Comment by rodfersou** [comment]
@mauritsvanrees thank you very much!

**Comment by mauritsvanrees** [comment]
I have rebased, squashed and force pushed, so let Jenkins have another go at it for good measure:
http://jenkins.plone.org/job/pull-request-4.3/164/
Then I'll have a look at master.

**Comment by mauritsvanrees** [comment]
Just as I thought: Jenkins stays green.

**Pull request merged**
