### PR TITLE
Adds documentation for what the 'direction' parameter actually does

### PR DESCRIPTION
**Pull request by shadowmint**

### CODE REVIEW

**Comment by jensens** [comment]
hi @shadowmint - thanks for the contribution. I can not find you in the list of Plone contributors. This might be a mistake or you did not sign the Plone Contributor Agreement. If you plan to contribute more often (greatly appreciated!) I invite you to become core contributor by signing https://plone.org/foundation/contributors-agreement
Since this PR is about documentation I kindly ask @esteele if we can merge this anyway?

**Comment by gforcada** [comment]
@shadowmint ping

**Comment by shadowmint** [comment]
hm? I have no interest in signing the plone contributors agreement and faxing a copy of it to someone.

If you don't want the change, close the PR and continue as ever. If you want it, merge it.

/shrug

**Comment by thet** [comment]
@esteele ping

A documentation contribution might not count as copyrightable creative work, especially when it describes functionality, which is already implemented.

https://plone.org/foundation/materials/foundation-resolutions/patch-policy-052011 does not explicitly mention contributions to documentation. maybe this should be fixed.

**Comment by thet** [comment]
Actually, the doc change is copied from: https://github.com/plone/plone.scale/blob/master/plone/scale/scale.py#L69
So this pull request is no copyrightable creative work.

Thanks for the contribution anyways, @shadowmint! This is greatly appreciated.

**Comment by jensens** [comment]
@thet since this is just copy paste I agree.

**Pull request merged**
